title: Jé le potier
description: >
  Site de vente de céramiques destiné à la préparation et au service du thé traditionnel.
author: pntbr
email: pntbr@scopyleft.fr
repository: jelepotier/presentation.git

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

collections_dir: ressources

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
